robot:
  name: $name
  creature: $creature
  camera: on

info:
  version: 1.0
  logfile: /tmp/puppet-master.log
  board: $board

update:
  url: https://raw.githubusercontent.com/pierre-rouanet/raspoppy/master/auto-update.sh
  logfile: $home/.install.log
  lockfile: /tmp/poppy-update-pid.lock
