# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_robot_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='host',
        ),
        migrations.AddField(
            model_name='robot',
            name='alive',
            field=models.BooleanField(default=False),
        ),
    ]
