# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20161006_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
