# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_robot_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='test',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
