# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_info_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='test',
        ),
        migrations.AddField(
            model_name='info',
            name='host',
            field=models.CharField(default='roboticia', max_length=50),
        ),
    ]
