# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_info_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daemon',
            name='type',
            field=models.CharField(default='snap', max_length=20),
        ),
    ]
