# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20161008_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daemon',
            name='running',
        ),
        migrations.AlterField(
            model_name='daemon',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='daemon',
            name='pid',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='daemon',
            name='type',
            field=models.CharField(default='http', max_length=20),
        ),
    ]
