# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20161008_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='pid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
