# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20161009_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='pid',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
