# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20161009_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='simulator',
            field=models.CharField(default='no', max_length=20),
        ),
    ]
