# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_daemon_simulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='logfile',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
