# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_daemon_logfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='log',
            field=models.TextField(default='none'),
        ),
    ]
