# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20170127_0018'),
        ('app1', '0002_info_test'),
    ]

    operations = [
    ]
