# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_robot_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='test',
        ),
        migrations.AddField(
            model_name='robot',
            name='camera',
            field=models.BooleanField(default=True),
        ),
    ]
