# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20170127_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='simulated',
            field=models.BooleanField(default=False),
        ),
    ]
