# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_robot_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
