# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_info_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='test',
        ),
    ]
