# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20170127_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='simulated',
            new_name='type',
        ),
    ]
