# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20170127_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='type',
            field=models.CharField(choices=[('V', 'vrep'), ('S', 'poppy-simu'), ('R', 'real robot')], default='R', max_length=1),
        ),
    ]
